defaults: &defaults 
    working_directory: ~/build
    docker: 
      - image: joshhsoj1902/circleci-build-image:1.0.3@sha256:8037436d356e7854ff9f325bf9e27b231036eba75211e603ef408e911a522aba
remote_docker_version: &remote_docker_version
    version: 17.11.0-ce

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *remote_docker_version
      - run:
          name: "Build image"
          command: |
            make build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

