defaults: &defaults 
    working_directory: ~/ogp
    machine: true
    environment:
      DOCKER_URL: https://download.docker.com/linux/static/edge/x86_64/docker-17.05.0-ce.tgz
      DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Upgrade Docker
          command: |
            curl -sSL $DOCKER_URL | sudo tar -xz --strip-components=1 -C /usr/bin/
            sudo service docker restart
      - run:
          name: "Build image"
          command: |
            make build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

